export interface Template {
  id: string;
  name: string;
  desc: string;
  category: "story" | "conversation" | "quiz" | "reaction" | "educational";
  icon: string;
  defaults: Record<string, any>;
  fields: TemplateField[];
}

export interface TemplateField {
  key: string;
  label: string;
  type: "text" | "textarea" | "select" | "toggle" | "slider";
  placeholder?: string;
  options?: { value: string; label: string }[];
  default?: any;
  min?: number;
  max?: number;
  step?: number;
}

export const TEMPLATES: Template[] = [
  {
    id: "reddit_story",
    name: "Reddit Story",
    desc: "Reddit post with gameplay background + AI voiceover",
    category: "story",
    icon: "📱",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "redditUrl",
        label: "Reddit URL",
        type: "text",
        placeholder: "https://reddit.com/r/...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Male)" },
          { value: "en-US-AndrewNeural", label: "Andrew (Male)" },
          { value: "en-US-BrianNeural", label: "Brian (Male)" },
          { value: "en-US-AriaNeural", label: "Aria (Female)" },
          { value: "en-US-AvaNeural", label: "Ava (Female)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "ai_story",
    name: "AI Story",
    desc: "AI-generated story with dramatic captions",
    category: "story",
    icon: "✨",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "word_by_word",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Story Text",
        type: "textarea",
        placeholder: "Write your story or paste a script...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Male, Authority)",
          },
          { value: "en-US-GuyNeural", label: "Guy (Male, Casual)" },
          { value: "en-US-AvaNeural", label: "Ava (Female, Friendly)" },
          { value: "en-US-EmmaNeural", label: "Emma (Female, Cheerful)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "shake", label: "Shake" },
          { value: "colorful", label: "Colorful" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "minimal", label: "Minimal" },
        ],
        default: "word_by_word",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "fake_text",
    name: "Fake Text",
    desc: "iMessage-style text conversation",
    category: "conversation",
    icon: "💬",
    defaults: {
      type: "fake_text",
      fontSize: 32,
      senderName: "Contact",
    },
    fields: [
      {
        key: "senderName",
        label: "Contact Name",
        type: "text",
        placeholder: "Contact name",
        default: "Contact",
      },
      {
        key: "messages",
        label: "Messages (Me: / Them: format)",
        type: "textarea",
        placeholder: "Me: Hey!\nThem: What's up?\nMe: Not much",
      },
    ],
  },
  {
    id: "split_screen",
    name: "Split Screen",
    desc: "Main video + gameplay background side by side",
    category: "reaction",
    icon: "🎬",
    defaults: {
      type: "split_screen",
      bgPosition: "left",
    },
    fields: [
      {
        key: "url",
        label: "Video URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "bgPosition",
        label: "Gameplay Position",
        type: "select",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
        ],
        default: "left",
      },
    ],
  },
  {
    id: "quiz",
    name: "Quiz / Trivia",
    desc: "Question with countdown and answer reveal",
    category: "quiz",
    icon: "🧠",
    defaults: {
      type: "story",
      voiceover: false,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
    },
    fields: [
      {
        key: "question",
        label: "Question",
        type: "text",
        placeholder: "What is the capital of France?",
      },
      { key: "answer", label: "Answer", type: "text", placeholder: "Paris" },
      {
        key: "options",
        label: "Options (comma-separated)",
        type: "text",
        placeholder: "Paris, London, Berlin, Madrid",
      },
      {
        key: "timer",
        label: "Countdown (seconds)",
        type: "select",
        options: [
          { value: "3", label: "3 seconds" },
          { value: "5", label: "5 seconds" },
          { value: "7", label: "7 seconds" },
          { value: "10", label: "10 seconds" },
        ],
        default: "5",
      },
    ],
  },
  {
    id: "scary_story",
    name: "Scary Story",
    desc: "Horror story with dark theme and eerie voice",
    category: "story",
    icon: "👻",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "minimal",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Scary Story",
        type: "textarea",
        placeholder: "Write your horror story...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-ChristopherNeural", label: "Christopher (Deep)" },
          { value: "en-US-BrianNeural", label: "Brian (Soft)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "minimal", label: "Minimal" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "typewriter", label: "Typewriter" },
        ],
        default: "minimal",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "advice",
    name: "Life Advice",
    desc: "Motivational quote or life lesson with dramatic captions",
    category: "educational",
    icon: "💡",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "colorful",
      voice: "en-US-AvaNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Advice / Quote",
        type: "textarea",
        placeholder: "The only way to do great work is to love what you do...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-AvaNeural", label: "Ava (Female, Warm)" },
          { value: "en-US-AndrewNeural", label: "Andrew (Male, Confident)" },
        ],
        default: "en-US-AvaNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "colorful", label: "Colorful" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "colorful",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "pov_story",
    name: "POV Story",
    desc: "First-person perspective story with you-centric captions",
    category: "story",
    icon: "🎥",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "POV Story",
        type: "textarea",
        placeholder:
          "POV: You walk into a room and notice something strange...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Casual)" },
          { value: "en-US-AvaNeural", label: "Ava (Friendly)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "typewriter", label: "Typewriter" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "auto_clip",
    name: "Auto Clip",
    desc: "Paste a YouTube URL → auto-detect best moments → extract highlight clips",
    category: "story",
    icon: "✂️",
    defaults: {
      type: "story",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "none",
      smartZoom: false,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "url",
        label: "YouTube / TikTok URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 10,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
    ],
  },
  {
    id: "sermon_clip",
    name: "Sermon Clip",
    desc: "YouTube sermon → auto-detect highlights → captioned clips with hook intro",
    category: "story",
    icon: "⛪",
    defaults: {
      type: "sermon_clip",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      hookIntro: "Watch this...",
      silenceRemoval: false,
    },
    fields: [
      {
        key: "url",
        label: "YouTube Sermon URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "hookIntro",
        label: "Hook Intro Text",
        type: "text",
        placeholder: "Watch this...",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 10,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Sermon Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
      {
        key: "silenceRemoval",
        label: "Remove Silence",
        type: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "sermon_quote",
    name: "Sermon Quote",
    desc: "Single powerful quote with dramatic text reveal",
    category: "story",
    icon: "📖",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "zoom",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.2,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Quote",
        type: "textarea",
        placeholder:
          '"For God so loved the world that he gave his one and only Son..."',
      },
      {
        key: "attribution",
        label: "Attribution (optional)",
        type: "text",
        placeholder: "John 3:16",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Authority)",
          },
          { value: "en-US-GuyNeural", label: "Guy (Warm)" },
          { value: "en-US-AvaNeural", label: "Ava (Gentle)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Text Style",
        type: "select",
        options: [
          { value: "zoom", label: "Zoom Reveal" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "bold_pop", label: "Bold Pop" },
        ],
        default: "zoom",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.2,
      },
    ],
  },
  {
    id: "testimony",
    name: "Testimony",
    desc: "Personal testimony with emotional captions + dramatic music",
    category: "story",
    icon: "🕊️",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "word_by_word",
      voice: "en-US-AvaNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.25,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Testimony Story",
        type: "textarea",
        placeholder:
          "I was lost for years. I struggled with addiction, depression, and hopelessness...",
      },
      {
        key: "speakerName",
        label: "Speaker Name (optional)",
        type: "text",
        placeholder: "Sarah's Testimony",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-AvaNeural", label: "Ava (Female, Warm)" },
          { value: "en-US-EmmaNeural", label: "Emma (Female, Gentle)" },
          { value: "en-US-GuyNeural", label: "Guy (Male, Calm)" },
          { value: "en-US-BrianNeural", label: "Brian (Male, Soft)" },
        ],
        default: "en-US-AvaNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "colorful", label: "Colorful" },
          { value: "glow", label: "Glow" },
        ],
        default: "word_by_word",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.25,
      },
    ],
  },
  {
    id: "podcast_clip",
    name: "Podcast Clip",
    desc: "YouTube podcast → auto-detect highlights → captioned clips",
    category: "story",
    icon: "🎙️",
    defaults: {
      type: "podcast_clip",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.1,
      silenceRemoval: false,
    },
    fields: [
      {
        key: "url",
        label: "YouTube Podcast URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 10,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Audio Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.1,
      },
      {
        key: "silenceRemoval",
        label: "Remove Silence",
        type: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "reaction",
    name: "Reaction",
    desc: "React to a video — picture-in-picture with commentary",
    category: "reaction",
    icon: "😲",
    defaults: {
      type: "reaction",
      pipPosition: "bottom-right",
      pipSize: 0.3,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "mainUrl",
        label: "Main Video URL (what you're reacting to)",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "reactionUrl",
        label: "Reaction Video URL (your face cam)",
        type: "text",
        placeholder: "https://youtube.com/watch?v=... or local file",
      },
      {
        key: "pipPosition",
        label: "Your Camera Position",
        type: "select",
        options: [
          { value: "bottom-right", label: "Bottom Right" },
          { value: "bottom-left", label: "Bottom Left" },
          { value: "top-right", label: "Top Right" },
          { value: "top-left", label: "Top Left" },
        ],
        default: "bottom-right",
      },
      {
        key: "pipSize",
        label: "Camera Size",
        type: "slider",
        min: 0.15,
        max: 0.5,
        step: 0.05,
        default: 0.3,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
    ],
  },
  {
    id: "top_list",
    name: "Top 5 / List",
    desc: 'Countdown list with dramatic reveals — "Top 5 reasons..."',
    category: "educational",
    icon: "🔢",
    defaults: {
      type: "top_list",
      voiceover: false,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: false,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      revealDuration: 3,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "title",
        label: "List Title",
        type: "text",
        placeholder: "Top 5 Signs You're Growing Closer to God",
      },
      {
        key: "items",
        label: "List Items (one per line)",
        type: "textarea",
        placeholder:
          "You pray without being asked\nYou forgive faster\nYou feel peace in chaos\nYou crave Scripture\nYour relationships improve",
      },
      {
        key: "voice",
        label: "Voice (for narration)",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Casual)" },
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Authority)",
          },
          { value: "en-US-AvaNeural", label: "Ava (Friendly)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "zoom", label: "Zoom Reveal" },
          { value: "bounce", label: "Bounce" },
          { value: "typewriter", label: "Typewriter" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "revealDuration",
        label: "Seconds per Item",
        type: "slider",
        min: 2,
        max: 8,
        step: 1,
        default: 3,
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
];

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): Template[] {
  return TEMPLATES.filter((t) => t.category === category);
}
